from app.routes import auth
from app.routes import careers
from app.routes import dashboard
from app.routes import interviews
from app.routes import jobs
from app.routes import market
from app.routes import notifications
from app.routes import profile
from app.routes import projects
from app.routes import resources
from app.routes import resume
from app.routes import skills
from app.routes import study
