"""Portfolio project templates mapped to roadmap skills.
skill_keys reference career-local skill keys."""

PROJECTS = [
    # ---------------- AI/ML Engineer ----------------
    {"career": "ai-ml-engineer", "difficulty": "beginner", "hours": 25,
     "title": "End-to-End House Price Predictor",
     "description": "Build a complete classical ML pipeline: clean raw housing data, engineer features, train and compare regression models, then serve predictions through a FastAPI endpoint with a small web UI.",
     "technologies": ["Python", "scikit-learn", "Pandas", "FastAPI"],
     "skills": ["python", "pandas", "numpy", "scikit-learn", "feature-engineering", "fastapi"],
     "milestones": [
         {"title": "Data exploration & cleaning", "description": "Profile missing values, outliers, correlations; document findings in a notebook."},
         {"title": "Feature pipeline", "description": "Build a reproducible sklearn Pipeline with encoding + scaling."},
         {"title": "Model selection", "description": "Compare LinearRegression, RandomForest, XGBoost with cross-validation; pick by RMSE."},
         {"title": "API service", "description": "Wrap the model in FastAPI with Pydantic input validation and tests."}],
     "deliverables": ["GitHub repo with README", "Jupyter analysis notebook", "Dockerized FastAPI service", "Metrics report"],
     "rubric": [{"criterion": "Reproducibility (env, seeds, data versioning)", "weight": 20},
                {"criterion": "Feature engineering rigor", "weight": 25},
                {"criterion": "Evaluation methodology", "weight": 25},
                {"criterion": "Code quality & API design", "weight": 30}]},

    {"career": "ai-ml-engineer", "difficulty": "intermediate", "hours": 45,
     "title": "Image Classifier with Transfer Learning",
     "description": "Fine-tune a pretrained CNN (ResNet/EfficientNet) on a custom dataset, track experiments, and deploy as a containerized REST service with monitoring.",
     "technologies": ["PyTorch", "torchvision", "MLflow", "Docker", "FastAPI"],
     "skills": ["deep-learning", "pytorch", "matplotlib", "docker", "model-deployment"],
     "milestones": [
         {"title": "Dataset preparation", "description": "Curate/augment an image dataset; create train/val/test splits."},
         {"title": "Transfer learning baseline", "description": "Fine-tune a pretrained backbone; log runs to MLflow."},
         {"title": "Experimentation", "description": "Tune LR schedules, augmentation, unfreezing strategy; record ablations."},
         {"title": "Deployment", "description": "Serve via Docker + FastAPI; add health check and latency logging."}],
     "deliverables": ["Trained model checkpoint", "Experiment tracking dashboard", "Containerized inference API", "README with results table"],
     "rubric": [{"criterion": "Training correctness (no leakage)", "weight": 25},
                {"criterion": "Experimental rigor", "weight": 25},
                {"criterion": "Deployment quality", "weight": 30},
                {"criterion": "Documentation", "weight": 20}]},

    {"career": "ai-ml-engineer", "difficulty": "advanced", "hours": 70,
     "title": "RAG Knowledge Assistant",
     "description": "Build a production-grade retrieval-augmented chatbot over your own documents: chunking, embeddings, vector store, hybrid retrieval, guardrails, evaluation harness and streaming UI.",
     "technologies": ["LangChain", "ChromaDB", "OpenAI/HF models", "Next.js", "Docker"],
     "skills": ["transformers", "llms-rag", "vector-databases", "fastapi", "docker", "model-deployment"],
     "milestones": [
         {"title": "Ingestion pipeline", "description": "Parse PDFs/HTML, smart chunking, embed into vector DB."},
         {"title": "Retrieval & generation", "description": "Implement hybrid search (BM25 + vectors) and grounded prompting with citations."},
         {"title": "Evaluation harness", "description": "Golden-question set; measure faithfulness and retrieval hit-rate automatically."},
         {"title": "Product surface", "description": "Streaming chat UI with source display and refusal behavior."}],
     "deliverables": ["Working RAG app", "Eval report with metrics", "Architecture diagram", "Demo video or live link"],
     "rubric": [{"criterion": "Retrieval quality", "weight": 30},
                {"criterion": "Answer faithfulness / hallucination control", "weight": 30},
                {"criterion": "Engineering polish", "weight": 25},
                {"criterion": "Evaluation methodology", "weight": 15}]},

    # ---------------- Data Scientist ----------------
    {"career": "data-scientist", "difficulty": "beginner", "hours": 20,
     "title": "Exploratory Analysis: Netflix/Titanic Dataset",
     "description": "Pick a public dataset and produce a polished exploratory analysis: cleaning decisions, visual storytelling and 5 actionable insights written for a non-technical audience.",
     "technologies": ["Python", "Pandas", "Seaborn", "Jupyter"],
     "skills": ["python", "pandas", "eda", "matplotlib", "communication"],
     "milestones": [
         {"title": "Data audit", "description": "Document schema, missingness and quality issues."},
         {"title": "Univariate + bivariate EDA", "description": "Systematic profiling with clear charts."},
         {"title": "Insight synthesis", "description": "Write 5 insights ranked by business relevance."},
         {"title": "Presentation", "description": "Assemble a short slide-style notebook summary."}],
     "deliverables": ["Cleaned dataset", "EDA notebook", "Insight write-up"],
     "rubric": [{"criterion": "Analytical depth", "weight": 35},
                {"criterion": "Visualization clarity", "weight": 30},
                {"criterion": "Communication", "weight": 35}]},

    {"career": "data-scientist", "difficulty": "intermediate", "hours": 40,
     "title": "Customer Churn Prediction & Dashboard",
     "description": "Predict telecom churn with proper validation, translate model output into retention segments, and ship an interactive Tableau/BI dashboard for stakeholders.",
     "technologies": ["Python", "scikit-learn", "SQL", "Tableau Public"],
     "skills": ["sql", "machine-learning", "scikit-learn", "feature-engineering", "tableau", "business-acumen"],
     "milestones": [
         {"title": "SQL feature mart", "description": "Build features with window functions directly in SQL."},
         {"title": "Model development", "description": "Logistic regression vs gradient boosting with PR-AUC focus."},
         {"title": "Segmentation", "description": "Translate risk scores into actionable tiers with expected-value math."},
         {"title": "Dashboard", "description": "Publish churn drivers + tier movement dashboard."}],
     "deliverables": ["Feature SQL scripts", "Model card", "Public dashboard link", "Executive one-pager"],
     "rubric": [{"criterion": "Methodological soundness", "weight": 30},
                {"criterion": "Business framing", "weight": 30},
                {"criterion": "Dashboard usability", "weight": 25},
                {"criterion": "Documentation", "weight": 15}]},

    {"career": "data-scientist", "difficulty": "advanced", "hours": 55,
     "title": "A/B Test Design & Causal Analysis Suite",
     "description": "Design a full experimentation framework: power analysis, randomization checks, sequential testing guardrails, plus a quasi-experimental causal study using difference-in-differences.",
     "technologies": ["Python", "statsmodels", "SQL", "Plotly"],
     "skills": ["statistics", "a-b-testing", "time-series", "eda", "communication"],
     "milestones": [
         {"title": "Simulation engine", "description": "Simulate experiments to validate power/sample-size math."},
         {"title": "Analysis library", "description": "Reusable functions: SRM checks, CUPED, confidence sequences."},
         {"title": "Causal case study", "description": "DiD/Synthetic control on public policy dataset."},
         {"title": "Decision memo", "description": "Write a launch/no-launch recommendation with uncertainty."}],
     "deliverables": ["Python package", "Case-study notebook", "Decision memo PDF"],
     "rubric": [{"criterion": "Statistical correctness", "weight": 40},
                {"criterion": "Practical applicability", "weight": 25},
                {"criterion": "Communication", "weight": 35}]},

    # ---------------- Full Stack Developer ----------------
    {"career": "full-stack-developer", "difficulty": "beginner", "hours": 30,
     "title": "Task Manager SPA",
     "description": "A responsive task manager with authentication-free local persistence, covering component composition, forms, routing and polished UI states (loading/error/empty).",
     "technologies": ["React", "TypeScript", "Tailwind CSS", "React Router"],
     "skills": ["html", "css", "javascript", "react", "tailwind-css"],
     "milestones": [
         {"title": "UI foundation", "description": "Component library: Button, Input, Modal with Tailwind."},
         {"title": "Core features", "description": "CRUD tasks with filters, drag-order and localStorage sync."},
         {"title": "Polish", "description": "Keyboard shortcuts, empty/loading states, mobile responsiveness."}],
     "deliverables": ["Live demo link", "GitHub repo", "Component docs"],
     "rubric": [{"criterion": "UI quality & responsiveness", "weight": 35},
                {"criterion": "React patterns", "weight": 30},
                {"criterion": "Accessibility basics", "weight": 20},
                {"criterion": "Code organization", "weight": 15}]},

    {"career": "full-stack-developer", "difficulty": "intermediate", "hours": 60,
     "title": "Full-Stack Blog Platform with Auth",
     "description": "Production-style blogging app: JWT auth, role-based access, Postgres schema, REST API with tests, React frontend, CI pipeline and cloud deployment.",
     "technologies": ["React", "Node.js", "Express", "PostgreSQL", "Jest", "GitHub Actions"],
     "skills": ["typescript", "nodejs", "rest-apis", "postgresql", "web-security", "testing", "ci-cd", "aws"],
     "milestones": [
         {"title": "Database schema & migrations", "description": "Design normalized schema; automate migrations."},
         {"title": "Auth & security", "description": "Hashed passwords, refresh tokens, rate limiting, OWASP hygiene."},
         {"title": "API + tests", "description": "REST endpoints with integration tests >80% coverage on routes."},
         {"title": "Frontend + deploy", "description": "React client; CI/CD deploying both tiers to cloud."}],
     "deliverables": ["Deployed application", "API documentation", "Test suite", "Architecture README"],
     "rubric": [{"criterion": "Security implementation", "weight": 30},
                {"criterion": "Backend architecture", "weight": 25},
                {"criterion": "Test coverage", "weight": 20},
                {"criterion": "Deployment automation", "weight": 25}]},

    {"career": "full-stack-developer", "difficulty": "advanced", "hours": 90,
     "title": "Scalable Realtime Chat & Collaboration App",
     "description": "Discord-lite: WebSocket realtime messaging, presence, message history pagination, caching layer, horizontal scaling design and load-tested deployment.",
     "technologies": ["Next.js", "Socket.IO/WebSockets", "Redis", "PostgreSQL", "Docker", "AWS"],
     "skills": ["nextjs", "system-design", "postgresql", "docker", "aws", "web-performance"],
     "milestones": [
         {"title": "Realtime foundation", "description": "Socket server with rooms, presence heartbeats, reconnect logic."},
         {"title": "History at scale", "description": "Cursor-paginated history, Redis hot cache, read replicas plan."},
         {"title": "Load testing", "description": "k6 scenarios; identify and fix bottlenecks; publish numbers."},
         {"title": "Infra as code", "description": "Docker Compose -> cloud deploy diagram with scaling notes."}],
     "deliverables": ["Running multi-user demo", "Load-test report", "Scaling architecture doc"],
     "rubric": [{"criterion": "Realtime correctness", "weight": 30},
                {"criterion": "Scalability thinking", "weight": 30},
                {"criterion": "Performance evidence", "weight": 25},
                {"criterion": "Ops maturity", "weight": 15}]},

    # ---------------- DevOps Engineer ----------------
    {"career": "devops-engineer", "difficulty": "beginner", "hours": 25,
     "title": "Dockerized Three-Tier Web App",
     "description": "Containerize a frontend + API + database stack with compose networking, healthchecks, volumes and sensible image hygiene (multi-stage, non-root).",
     "technologies": ["Docker", "Docker Compose", "Linux", "Nginx"],
     "skills": ["linux", "docker", "networking"],
     "milestones": [
         {"title": "Single-service images", "description": "Multi-stage builds under 150MB, non-root users."},
         {"title": "Compose orchestration", "description": "Networks, depends_on with healthchecks, env config."},
         {"title": "Local TLS + proxy", "description": "Nginx reverse proxy with self-signed certs."}],
     "deliverables": ["Compose stack", "Hardened Dockerfiles", "Runbook README"],
     "rubric": [{"criterion": "Image hygiene", "weight": 30},
                {"criterion": "Orchestration correctness", "weight": 30},
                {"criterion": "Documentation", "weight": 20},
                {"criterion": "Security practices", "weight": 20}]},

    {"career": "devops-engineer", "difficulty": "intermediate", "hours": 50,
     "title": "GitOps Microservice Platform on Kubernetes",
     "description": "Stand up a mini platform: Terraform-provisioned cluster (k3s/EKS), Argo CD deployments from Git, Helm charts, sealed secrets, Prometheus/Grafana observability.",
     "technologies": ["Kubernetes", "Argo CD", "Helm", "Terraform", "Prometheus", "Grafana"],
     "skills": ["kubernetes", "terraform", "gitops", "monitoring-observability", "cloud-security"],
     "milestones": [
         {"title": "Cluster provisioning", "description": "Repeatable cluster bring-up via Terraform."},
         {"title": "GitOps delivery", "description": "App-of-apps pattern with Argo CD; automated sync policies."},
         {"title": "Observability", "description": "Prometheus metrics, Grafana dashboards, alert rules."},
         {"title": "Secret management", "description": "Sealed secrets or external secrets operator end-to-end."}],
     "deliverables": ["IaC repository", "GitOps repo", "Dashboard screenshots/alerts", "Cost & sizing notes"],
     "rubric": [{"criterion": "Reproducibility of infra", "weight": 30},
                {"criterion": "GitOps fidelity", "weight": 25},
                {"criterion": "Observability completeness", "weight": 25},
                {"criterion": "Secrets handling", "weight": 20}]},

    {"career": "devops-engineer", "difficulty": "advanced", "hours": 60,
     "title": "Production CI/CD with Progressive Delivery",
     "description": "Enterprise-grade pipeline: trunk-based flow, canary releases with automatic rollback on SLO breach, ephemeral preview environments per PR, full audit trail.",
     "technologies": ["GitHub Actions", "Kubernetes", "Argo Rollouts", "Terraform", "Prometheus"],
     "skills": ["ci-cd", "kubernetes", "monitoring-observability", "sre-practices", "gitops"],
     "milestones": [
         {"title": "Pipeline core", "description": "Lint->test->build->scan->sign->deploy stages with caching."},
         {"title": "Canary automation", "description": "Metric-gated rollouts; auto-rollback demonstration."},
         {"title": "Preview environments", "description": "Namespace-per-PR lifecycle with TTL cleanup."},
         {"title": "Reliability drill", "description": "Chaos test: kill pods/nodes; verify SLO-based response."}],
     "deliverables": ["Pipeline repo", "Rollout demo video", "Incident-drill writeup"],
     "rubric": [{"criterion": "Pipeline sophistication", "weight": 30},
                {"criterion": "Progressive delivery correctness", "weight": 30},
                {"criterion": "Reliability evidence", "weight": 25},
                {"criterion": "Docs & auditability", "weight": 15}]},

    # ---------------- Cybersecurity Analyst ----------------
    {"career": "cybersecurity-analyst", "difficulty": "beginner", "hours": 25,
     "title": "Home Security Lab & Network Baseline",
     "description": "Build a virtual lab (attacker box + targets), capture traffic, learn Wireshark deeply and produce a network baseline document identifying anomalies.",
     "technologies": ["VirtualBox", "Kali Linux", "Wireshark", "Nmap"],
     "skills": ["networking", "linux", "vulnerability-assessment"],
     "milestones": [
         {"title": "Lab construction", "description": "Isolated virtual networks; snapshot discipline."},
         {"title": "Traffic capture", "description": "Generate benign + attack traffic; save pcaps."},
         {"title": "Analysis report", "description": "Annotate handshake, DNS, suspicious flows in Wireshark."}],
     "deliverables": ["Lab setup guide", "Pcap collection", "Baseline/anomaly report"],
     "rubric": [{"criterion": "Technical setup quality", "weight": 30},
                {"criterion": "Analysis accuracy", "weight": 40},
                {"criterion": "Report clarity", "weight": 30}]},

    {"career": "cybersecurity-analyst", "difficulty": "intermediate", "hours": 45,
     "title": "Web App Vulnerability Assessment Report",
     "description": "Assess OWASP Juice Shop like a professional: systematic scanning, manual exploitation within scope, CVSS scoring and a remediation-focused pentest report.",
     "technologies": ["Burp Suite", "OWASP Juice Shop", "Nmap", "CVSS"],
     "skills": ["owasp-top-10", "web-app-security", "vulnerability-assessment", "penetration-testing"],
     "milestones": [
         {"title": "Scope & recon", "description": "Rules of engagement; passive mapping; attack surface inventory."},
         {"title": "Exploitation", "description": "Confirm top-10 vulns manually; document reproduction steps."},
         {"title": "Reporting", "description": "Professional findings: severity, impact, remediation, retest criteria."}],
     "deliverables": ["Findings spreadsheet", "Full pentest report PDF", "Remediation checklist"],
     "rubric": [{"criterion": "Finding validity & depth", "weight": 40},
                {"criterion": "Report professionalism", "weight": 35},
                {"criterion": "Ethics/scope discipline", "weight": 25}]},

    {"career": "cybersecurity-analyst", "difficulty": "advanced", "hours": 55,
     "title": "Detection Engineering: Build Your Own SOC Rules",
     "description": "Ship detections end-to-end: centralize logs from attack simulations, write Sigma/YARA rules, tune false positives, map coverage to MITRE ATT&CK and automate alert triage.",
     "technologies": ["Elastic/Wazuh", "Sigma", "YARA", "Python", "MITRE ATT&CK Navigator"],
     "skills": ["siem", "incident-response", "threat-intelligence", "python-scripting"],
     "milestones": [
         {"title": "Telemetry pipeline", "description": "Collect sysmon/auth/web logs into SIEM."},
         {"title": "Rule authoring", "description": "10+ Sigma rules covering ATT&CK techniques; test against simulations."},
         {"title": "Tuning & automation", "description": "Reduce FP rate; auto-enrich alerts with Python playbooks."},
         {"title": "Coverage matrix", "description": "ATT&CK Navigator heat map of detection coverage."}],
     "deliverables": ["SIEM instance", "Rule repository", "Coverage matrix", "Tuning journal"],
     "rubric": [{"criterion": "Detection efficacy", "weight": 40},
                {"criterion": "ATT&CK mapping rigor", "weight": 25},
                {"criterion": "Automation value", "weight": 20},
                {"criterion": "Documentation", "weight": 15}]},
]
